Object gem
name diamond
harvest_race random_mininggems
harvest_exhaust_replacement blackrock
type 20
harvest_tool pickaxe
harvestable -1
harvest_level 1
harvest_exp 0
type 60
face gem.111
animation gem
nrof 1
anim_speed 10
client_anim_random 1
value 400
weight 50
material 64
identified 1
name_pl diamonds
client_type 2011
end
